### ISSUE TITLE
Can't run Android. Cannot invoke method ndk() on null object

### ISSUE THREAD

**Issue by rajatsinghal** [f111fei/react-native-unity-demo#19]
Error: Cannot invoke method ndk() on null object

Output of running `./gradlew --stacktrace`:

Caused by: java.lang.NullPointerException: Cannot invoke method ndk() on null object
        at build_9w0ju6ghzv8qetl0kt4hr45xk$_run_closure3$_closure6.doCall(/Users/hitwicket/Code/ReactNative/HitwicketArenas/android/UnityExport/build.gradle:31)
        at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:71)
        at org.gradle.util.ConfigureUtil.configureTarget(ConfigureUtil.java:160)
        at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:106)
        at org.gradle.util.ConfigureUtil$1.execute(ConfigureUtil.java:123)
        at com.android.build.gradle.BaseExtension.defaultConfig(BaseExtension.java:431)
        at com.android.build.gradle.LibraryExtension_Decorated.defaultConfig(Unknown Source)
        at org.gradle.internal.metaobject.BeanDynamicObject$MetaClassAdapter.invokeMethod(BeanDynamicObject.java:464)
        at org.gradle.internal.metaobject.BeanDynamicObject.invokeMethod(BeanDynamicObject.java:176)
        at org.gradle.internal.metaobject.CompositeDynamicObject.invokeMethod(CompositeDynamicObject.java:96)

**Comment by tomaisthorpe** [comment]
This might be a bit late, but I had the same issue, so it's useful to document it.

It was due an issue in _android/UnityExport/build.gradle_.

On line 33, I had:
`targetSdkVersion 26		ndk {`

_ndk_ should be on a new line.
